### ISSUE TITLE
Syntax error while running test-sample

### ISSUE THREAD

**Issue by svenkanna** [cbpetersen/react-native-grpc-bridge-generator#1]
I tried running the test-sample provided. Here is what I got

babel test-samples/sample.proto 
SyntaxError: test-samples/sample.proto: package is a reserved word in strict mode (3:0)
  1 | syntax = "proto3";
  2 | 
> 3 | package api.grpc;
    | ^
  4 | 
  5 | service GrpcService {
  6 |     rpc ReverseGeocode(ReverseGeocodeRequest) returns (Location) {}

**Comment by cbpetersen** [comment]
The example might be outdated, could you try `node index.js --input=test-samples`

Otherwise i need some more info on how to reproduce it, as i can't seem to do it

**Comment by sercanov** [comment]
I had the same issue but `node index.js --input=test-samples` worked fine, thanks @cbpetersen !

**Comment by svenkanna** [comment]
node index.js --input=test-samples. worked for me too.
